@rem 安装程序所需模块
@echo off
chcp 65001
title 安装程序所需模块...
echo install module EasyGUI...
pip install easygui
echo install module ConfigParser...
pip install configparser
echo install module datetime...
pip install datetime
echo install module fuzzywuzzy...
pip install fuzzywuzzy
echo 按任意键继续
pause>nul
echo 完成
echo 请按任意键退出...
pause>nul